// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgktilawzoizgcpyeuok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1na3RpbGF3em9pemdjcHlldW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzE5OTUsImV4cCI6MjA1OTcwNzk5NX0.K0qzkFJoFckDiWc1EtfP_dORFbqBKlmL3bwlodXzFxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);